version: '3'

services:
  api:
    build:
      context: todo-back
    ports:
      - '3030'
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    hostname: mongodb
    ports:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo_data:/data/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./todo-front/build:/usr/share/nginx/html
    ports:
      - '80:80'

volumes:
  mongo_data:
